### ISSUE TITLE
Having a sample/example nuxt ssr project that I can use to deploy via fume.app

### ISSUE THREAD

**Issue by Phyrom** [fumeapp/discuss#14]
Hi,
I've tried almost 2 days to get the basic nuxt ssr deployed via fume.app, unfortunately I couldn't get it working. It gives me error as the following:

START RequestId: 7306e4b7-68e6-4890-a5fb-cc905809e68e Version: $LATEST
ERROR inject('content', value) has no value provided at inject (.nuxt/index.js:193:0) at plugin_server (.nuxt/content/plugin.server.js:9:0) at createApp (.nuxt/index.js:277:0) at async module.exports.__webpack_exports__.default (.nuxt/server.js:81:0)
END RequestId: 7306e4b7-68e6-4890-a5fb-cc905809e68e

I have no clue at all at this point

Appreciate if you can help guiding

Thanks,
Phyrom

**Comment by acidjazz** [comment]
Thank you for reaching out @Phyrom - please take a look at https://github.com/fumeapp/example
